typography_spectrum: 0.8930009312462062
color:
  brandStrength: 0.6884408674668521
  lightness: 0.6527474967297167
  saturation: 0.10022132098674774
  rhythmicContrast: 0.14125413727015257
  brandColors:
    - '#88A825'
    - '#35203B'
    - '#911146'
    - '#CF4A30'
    - '#ED8C2B'
layout_spectrum: 0.27886857208795846
name: simple crepes
title: 'Eggplant, Red Pepper, Feta & Basil Crepes'
description: 'Fast, furious and healthy ... check out your purple eggplant state'
